ai_provider_mittwald.settings:
  type: config_object
  label: 'mittwald Settings'
  mapping:
    api_key:
      type: string
      label: 'The API key for mittwald via Key module'
    moderation:
      type: boolean
      label: 'Enable moderation requests before each request.'
    host:
      type: string
      label: 'The host to use for the API requests.'
